sudo: false

language: java

jdk:
  - oraclejdk8

env:
  - "IDEA_VERSION=IU-2016.1.3;PHP_PLUGIN_VERSION=145.970.40;TWIG_PLUGIN_VERSION=145.258.2"
  - "IDEA_VERSION=IU-2016.2;PHP_PLUGIN_VERSION=162.1121.34;TWIG_PLUGIN_VERSION=162.1121.34"
  - "IDEA_VERSION=IU-2016.2.5;PHP_PLUGIN_VERSION=162.1628.23;TWIG_PLUGIN_VERSION=162.1121.34"
  - "IDEA_VERSION=IU-2016.3;PHP_PLUGIN_VERSION=163.7743.20;TWIG_PLUGIN_VERSION=163.6110.10"
  - "IDEA_VERSION=IU-2016.3.3;PHP_PLUGIN_VERSION=163.10504.2;TWIG_PLUGIN_VERSION=163.9735.4"
  - "IDEA_VERSION=IU-2017.1;PHP_PLUGIN_VERSION=171.3780.104;TWIG_PLUGIN_VERSION=171.1834.12"
  - "IDEA_VERSION=IU-2017.2;PHP_PLUGIN_VERSION=172.3317.83;TWIG_PLUGIN_VERSION=172.2827.17"
  - "IDEA_VERSION=IU-2018.2.4;PHP_PLUGIN_VERSION=182.4505.42;TWIG_PLUGIN_VERSION=182.3458.35"
  - "IDEA_VERSION=IU-2018.3;PHP_PLUGIN_VERSION=183.4284.150;TWIG_PLUGIN_VERSION=183.3795.24"

script: ./gradlew test -DideaVersion=$IDEA_VERSION -DphpPluginVersion=$PHP_PLUGIN_VERSION -DtwigPluginVersion=$TWIG_PLUGIN_VERSION --exclude-task=compileJava

matrix:
  allow_failures: []